In [1]:
import numpy as np

In [2]:
ar1 = np.array([0, 1, 2, 3])

In [3]:
ar2 = np.array([[0,3, 5], [2, 8, 7]])

In [4]:
ar1

array([0, 1, 2, 3])

In [5]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [6]:
ar2.shape

(2, 3)

In [7]:
ar2.ndim

2

In [8]:
ar3 = np.arange(12); 

In [9]:
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
ar4 = np.arange(3, 10, 3); ar4

array([3, 6, 9])

In [11]:
# args - start element, end element, number of elements
ar5 = np.linspace(0, 2.0/3.4); ar5

array([ 0.        ,  0.0120048 ,  0.0240096 ,  0.03601441,  0.04801921,
        0.06002401,  0.07202881,  0.08403361,  0.09603842,  0.10804322,
        0.12004802,  0.13205282,  0.14405762,  0.15606242,  0.16806723,
        0.18007203,  0.19207683,  0.20408163,  0.21608643,  0.22809124,
        0.24009604,  0.25210084,  0.26410564,  0.27611044,  0.28811525,
        0.30012005,  0.31212485,  0.32412965,  0.33613445,  0.34813926,
        0.36014406,  0.37214886,  0.38415366,  0.39615846,  0.40816327,
        0.42016807,  0.43217287,  0.44417767,  0.45618247,  0.46818727,
        0.48019208,  0.49219688,  0.50420168,  0.51620648,  0.52821128,
        0.54021609,  0.55222089,  0.56422569,  0.57623049,  0.58823529])

In [12]:
# Produces 2x3x2 array of 1's
ar7 = np.ones((2, 3, 2)); ar7

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [13]:
ar8 = np.zeros((4, 2));ar8

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
ar10 = np.diag((2, 1, 4, 6));ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [16]:
# Using the rand, radn functions
np.random.seed(100)
ar11 = np.random.rand(3); ar11

array([ 0.54340494,  0.27836939,  0.42451759])

In [17]:
ar12 = np.random.rand(5); ar12

array([ 0.84477613,  0.00471886,  0.12156912,  0.67074908,  0.82585276])

In [18]:
ar13 = np.empty((3, 2)); ar13

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [19]:
np.array([[1, 2], [6, 7]])

array([[1, 2],
       [6, 7]])

In [20]:
np.tile(np.array([[1, 2], [6, 7]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [21]:
np.tile(np.array([[1, 2], [6, 7]]), (2, 2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

## Mastering Pandas (page 56 of 365)

In [22]:
ar = np.array([2, -1, 6, 3], dtype = 'float'); ar

array([ 2., -1.,  6.,  3.])

In [23]:
ar.dtype

dtype('float64')

In [24]:
ar = np.array([2, 4, 6, 8]); ar.dtype

dtype('int64')

In [25]:
ar = np.array([2., 4, 6, 8]); ar.dtype

dtype('float64')

In [26]:
sar = np.array(['Goodbye', 'Welcome', 'Tata', 'Goonight']); sar.dtype

dtype('<U8')

In [27]:
bar = np.array([True, False, True]); bar.dtype

dtype('bool')

In [28]:
f_ar = np.array([3, -2, 8.18]); f_ar

array([ 3.  , -2.  ,  8.18])

In [29]:
f_ar.astype(int)

array([ 3, -2,  8])

In [30]:
ar = np.arange(5); print(ar)

[0 1 2 3 4]


In [31]:
ar[0]

0

In [32]:
ar[1]

1

In [33]:
ar[-1]

4

In [34]:
ar = np.arange(5); ar[1], ar[-1], ar[0]

(1, 4, 0)

In [35]:
ar

array([0, 1, 2, 3, 4])

In [36]:
ar = np.arange(5); ar[::-1]

array([4, 3, 2, 1, 0])

In [37]:
ar = np.array([[2, 3, 4], [9, 8 , 7], [11, 12, 13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [38]:
ar[1, 1]

8

In [39]:
ar[1, 1]= 5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

In [40]:
ar[2]

array([11, 12, 13])

In [41]:
ar[2, :]

array([11, 12, 13])

In [42]:
ar[:, 1]

array([ 3,  5, 12])

In [43]:
ar = np.array([0, 1, 2])

In [46]:
ar[1:5:2]

array([2, 6])

In [47]:
ar[1:6:2]

array([2, 6])

In [48]:
ar[:4]

array([0, 2, 4, 6])

In [49]:
ar[4:]

array([8])

In [51]:
ar[::3]

array([0, 6])

In [52]:
ar

array([0, 2, 4, 6, 8])

In [53]:
ar[:3] = 1; ar

array([1, 1, 1, 6, 8])

In [55]:
np.random.seed(10)

In [56]:
ar = np.random.random_integers(0, 25, 10); ar

array([ 9,  4, 15,  0, 17, 25, 16, 17,  8,  9])

In [57]:
evenMask = (ar % 2 == 0); evenMask

array([False,  True, False,  True, False, False,  True, False,  True, False], dtype=bool)

In [58]:
evenNums = ar[evenMask]; evenNums

array([ 4,  0, 16,  8])

In [59]:
ar = np.array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'], 
      dtype='<U9')

In [60]:
ar[ar==''] = 'USA'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'], 
      dtype='<U9')

In [61]:
ar == 11*np.arange(0, 10); ar

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if __name__ == '__main__':


array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'], 
      dtype='<U9')

In [62]:
ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'], 
      dtype='<U9')

In [63]:
ar = np.arange(15); ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
ar2 = np.arange(0, -10, -1)[::-1]; ar2

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [65]:
ar[:10] = ar2; ar

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

In [66]:
ar1 = np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
ar2 = ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [68]:
ar2[1] = -1; ar1

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
ar = np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [70]:
arc = ar[:3].copy(); arc

array([0, 1, 2])

In [71]:
arc[0] = -1; arc

array([-1,  1,  2])

In [72]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
ar = np.arange(0, 7)*5; ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [74]:
ar = np.arange(5) ** 4 ; ar

array([  0,   1,  16,  81, 256])

In [75]:
ar ** 0.5

array([  0.,   1.,   4.,   9.,  16.])

In [76]:
ar = 3 + np.arange(0, 30, 3); ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [77]:
ar2 = np.arange(1, 11); ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
ar-ar2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
ar/ar2

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [80]:
ar*ar2

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [81]:
ar = np.arange(1000)
%timeit ar**3

The slowest run took 4.98 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 48.2 µs per loop


In [82]:
ar = range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 565 µs per loop


In [83]:
ar = np.array([[1,1], [1, 1]]); ar

array([[1, 1],
       [1, 1]])

In [84]:
ar2 = np.array([[2, 2], [2, 2]]); ar2

array([[2, 2],
       [2, 2]])

In [85]:
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

In [86]:
ar = np.arange(1, 5); ar

array([1, 2, 3, 4])

In [87]:
ar2 = np.arange(5, 1, -1); ar2

array([5, 4, 3, 2])

In [88]:
ar < ar2

array([ True,  True, False, False], dtype=bool)

In [89]:
l1 = np.array([True, False, True, False])
l2 = np.array([False, False, True, False])
np.logical_and(l1, l2)

array([False, False,  True, False], dtype=bool)

In [90]:
ar = np.array([np.pi, np.pi/2]); np.sin(ar)

array([  1.22464680e-16,   1.00000000e+00])

In [91]:
ar = np.arange(0, 6); ar

array([0, 1, 2, 3, 4, 5])

In [92]:
ar2 = np.arange(0, 8); ar2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [93]:
ar = np.array([[1, 2, 3], [4, 5, 6]]); ar

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [95]:
np.transpose(ar)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [96]:
ar = np.arange(0, 6)
ar2 = np.array([0, 1, 2, 3, 4, 5])
np.array_equal(ar, ar2)

True

In [97]:
np.all(ar == ar2)

True

In [98]:
ar = np.arange(1, 5)

In [99]:
ar.prod()

24

In [100]:
ar = np.array([np.arange(1, 6), np.arange(1, 6)]); ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [101]:
np.prod(ar, axis = 0)

array([ 1,  4,  9, 16, 25])

In [102]:
ar = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]]); ar.sum()

54

In [103]:
ar.mean()

6.0

In [104]:
np.median(ar)

6.0

In [105]:
np.random.seed(10)

In [106]:
ar = np.random.randint(0, 10, size = (4, 5)); ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [107]:
ar.mean()

4.4500000000000002

In [108]:
ar.std()

3.4274626183227732

In [109]:
ar.var(axis = 0) # across rows

array([ 12.6875,   4.1875,  11.    ,  10.75  ,  18.1875])

In [110]:
ar.cumsum()

array([ 9, 13, 13, 14, 23, 23, 24, 32, 41, 41, 49, 55, 59, 62, 62, 66, 72,
       80, 81, 89])

In [111]:
np.random.seed(100)

In [112]:
ar = np.random.randint(1, 10, size = (4, 4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [113]:
np.any((ar%7) == 0)

False

In [114]:
np.all(ar < 11)

True

In [115]:
ar = np.ones([3, 2]); ar

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [116]:
ar2 = np.array([2, 3]); ar2

array([2, 3])

In [117]:
ar + ar2

array([[ 3.,  4.],
       [ 3.,  4.],
       [ 3.,  4.]])

In [118]:
ar = np.array([[23, 24, 25]]); ar

array([[23, 24, 25]])

In [119]:
ar.T

array([[23],
       [24],
       [25]])

In [120]:
ar.T+ ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])

In [121]:
ar = np.array([np.arange(1, 6), np.arange(10, 15)]); ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [122]:
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [123]:
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [124]:
ar = np.arange(1, 16); ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [125]:
ar.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [126]:
ar = np.arange(5); ar.resize((8, )); ar

array([0, 1, 2, 3, 4, 0, 0, 0])

In [127]:
ar = np.arange(5); ar

array([0, 1, 2, 3, 4])

In [128]:
ar2 = ar

In [129]:
np.resize(ar, (8,))

array([0, 1, 2, 3, 4, 0, 1, 2])

In [130]:
ar = np.array([14, 15, 16]); ar.shape

(3,)

In [131]:
ar

array([14, 15, 16])

In [132]:
ar = ar[:, np.newaxis]; ar.shape

(3, 1)

In [133]:
ar

array([[14],
       [15],
       [16]])

In [134]:
ar = np.array([[3, 2], [10, -1]])

In [135]:
ar

array([[ 3,  2],
       [10, -1]])

In [136]:
ar.sort(axis = 1)

In [137]:
ar

array([[ 2,  3],
       [-1, 10]])

In [138]:
ar = np.array([[3, 2], [10, -1]])
ar

array([[ 3,  2],
       [10, -1]])

In [139]:
ar.sort(axis = 0)

In [140]:
ar

array([[ 3, -1],
       [10,  2]])

In [141]:
import pandas as pd

In [144]:
import numpy as np
np.random.seed(100)

In [145]:
ser = pd.Series(np.random.rand(7)); ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [146]:
import calendar as cal

In [147]:
monthNames = [cal.month_name[i] for i in np.arange(1, 6)]


In [149]:
months = pd.Series(np.arange(1, 6), index = monthNames); months

January     1
February    2
March       3
April       4
May         5
dtype: int64

In [150]:
months.index

Index(['January', 'February', 'March', 'April', 'May'], dtype='object')

In [151]:
currDict={'US' : 'dollar', 'UK' : 'pound',
                    'Germany': 'euro', 'Mexico':'peso',
                    'Nigeria':'naira',
                    'China':'yuan', 'Japan':'yen'}
currSeries = pd.Series(currDict); currSeries

China        yuan
Germany      euro
Japan         yen
Mexico       peso
Nigeria     naira
UK          pound
US         dollar
dtype: object

In [152]:
stockPrices = {'GOOG':1180.97,'FB':62.57,
                         'TWTR': 64.50, 'AMZN':358.69,
                         'AAPL':500.6}

In [153]:
stockPriceSeries = pd.Series(stockPrices, index = ['GOOG', 'FB', 'YHOO', 'TWTR', 'AMZN', 'AAPL'],
                            name = 'stockPrices')

In [154]:
stockPriceSeries

GOOG    1180.97
FB        62.57
YHOO        NaN
TWTR      64.50
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

In [155]:
dogSeries = pd.Series('chihuahua', index = ['breed', 'countryOfOrigin', 'name', 'gender'])

In [156]:
dogSeries

breed              chihuahua
countryOfOrigin    chihuahua
name               chihuahua
gender             chihuahua
dtype: object

In [157]:
dogSeries = pd.Series('pekingese'); dogSeries

0    pekingese
dtype: object

In [158]:
type(dogSeries)

pandas.core.series.Series

In [159]:
currDict['China']

'yuan'

In [160]:
stockPriceSeries['GOOG'] = 1200.0

In [161]:
stockPriceSeries

GOOG    1200.00
FB        62.57
YHOO        NaN
TWTR      64.50
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

In [164]:
stockPriceSeries.get('MSFT',np.NaN)

nan

In [165]:
stockPriceSeries[:4]

GOOG    1200.00
FB        62.57
YHOO        NaN
TWTR      64.50
Name: stockPrices, dtype: float64

In [166]:
stockPriceSeries[stockPriceSeries > 100]

GOOG    1200.00
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

In [167]:
np.mean(stockPriceSeries)

437.27200000000005

In [168]:
np.std(stockPriceSeries)

417.4446361087899

In [169]:
ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [170]:
ser*ser

0    0.295289
1    0.077490
2    0.180215
3    0.713647
4    0.000022
5    0.014779
6    0.449904
dtype: float64

In [171]:
np.sqrt(ser)

0    0.737160
1    0.527607
2    0.651550
3    0.919117
4    0.068694
5    0.348668
6    0.818993
dtype: float64

In [172]:
ser[1:]

1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [173]:
ser[1:] + ser[: -2]

0         NaN
1    0.556739
2    0.849035
3    1.689552
4    0.009438
5         NaN
6         NaN
dtype: float64

In [174]:
stockSummaries={
'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88],
        index=['Closing price','EPS',
                'Shares Outstanding(M)',
                'Beta', 'P/E','Market Cap(B)']),
'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'Beta','P/E','Market Cap(B)']),
'FB': pd.Series([61.48,0.59,2450,104.93,150.92],
      index=['Closing price','EPS','Shares Outstanding(M)',
             'P/E', 'Market Cap(B)']),
'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'P/E','Beta', 'Market Cap(B)']),
'TWTR':pd.Series([65.25,-0.3,555.2,36.23],
       index=['Closing price','EPS','Shares Outstanding(M)',
              'Market Cap(B)']),
'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],
       index=['Closing price','EPS','Shares Outstanding(M)','P/E',
              'Market Cap(B)','Beta'])}

In [175]:
stockDF = pd.DataFrame(stockSummaries); stockDF

AAPL    AMZN       FB     GOOG    TWTR     YHOO
Beta                     0.84    0.52      NaN     0.87     NaN     0.66
Closing price          501.53  346.15    61.48  1133.43   65.25    34.90
EPS                     40.32    0.59     0.59    36.05   -0.30     1.27
Market Cap(B)          447.59  158.88   150.92   380.64   36.23    35.36
P/E                     12.44  589.80   104.93    31.44     NaN    27.48
Shares Outstanding(M)  892.45  459.00  2450.00   335.83  555.20  1010.00

In [176]:
stockDF = pd.DataFrame(stockSummaries, index = ['Closing price', 'EPS', 
                                               'Shares Outstanding(M)', 'P/E',
                                               'Market Cap(B)', 'Beta'])

In [177]:
stockDF

AAPL    AMZN       FB     GOOG    TWTR     YHOO
Closing price          501.53  346.15    61.48  1133.43   65.25    34.90
EPS                     40.32    0.59     0.59    36.05   -0.30     1.27
Shares Outstanding(M)  892.45  459.00  2450.00   335.83  555.20  1010.00
P/E                     12.44  589.80   104.93    31.44     NaN    27.48
Market Cap(B)          447.59  158.88   150.92   380.64   36.23    35.36
Beta                     0.84    0.52      NaN     0.87     NaN     0.66

In [178]:
stockDF = pd.DataFrame(stockSummaries, 
                      index = ['Closing price', 'EPS', 
                              'Shares Outstanding(M)', 'P/E',
                              'Market Cap(B)', 'Beta'], 
                      columns = ['FB', 'TWTR', 'SCNW'])

In [179]:
stockDF

FB    TWTR SCNW
Closing price            61.48   65.25  NaN
EPS                       0.59   -0.30  NaN
Shares Outstanding(M)  2450.00  555.20  NaN
P/E                     104.93     NaN  NaN
Market Cap(B)           150.92   36.23  NaN
Beta                       NaN     NaN  NaN

In [180]:
stockDF.index

Index(['Closing price', 'EPS', 'Shares Outstanding(M)', 'P/E', 'Market Cap(B)',
       'Beta'],
      dtype='object')

In [181]:
stockDF.columns

Index(['FB', 'TWTR', 'SCNW'], dtype='object')

In [182]:
algos={'search':['DFS','BFS','Binary Search',
                 'Linear','ShortestPath (Djikstra)'],
      'sorting': ['Quicksort','Mergesort', 'Heapsort',
                   'Bubble Sort', 'Insertion Sort'],
      'machine learning':['RandomForest',
                           'K Nearest Neighbor',
                           'Logistic Regression',
                           'K-Means Clustering',
                           'Linear Regression']}


In [183]:
algoDF = pd.DataFrame(algos); algoDF

machine learning                   search         sorting
0         RandomForest                      DFS       Quicksort
1   K Nearest Neighbor                      BFS       Mergesort
2  Logistic Regression            Binary Search        Heapsort
3   K-Means Clustering                   Linear     Bubble Sort
4    Linear Regression  ShortestPath (Djikstra)  Insertion Sort

In [184]:
pd.DataFrame(algos, index = ['algo_1', 'algo_2', 'algo_3', 'algo_4', 'algo_5'])

machine learning                   search         sorting
algo_1         RandomForest                      DFS       Quicksort
algo_2   K Nearest Neighbor                      BFS       Mergesort
algo_3  Logistic Regression            Binary Search        Heapsort
algo_4   K-Means Clustering                   Linear     Bubble Sort
algo_5    Linear Regression  ShortestPath (Djikstra)  Insertion Sort

In [186]:
memberData = np.zeros((4,),
                dtype=[('Name','a15'),
                       ('Age','i4'),
                      ('Weight','f4')])
          

In [187]:
memberData[:] = [('Sanjeev',37,162.4),
                           ('Yingluck',45,137.8),
                           ('Emeka',28,153.2),
                           ('Amy',67,101.3)]

In [188]:
memberDF = pd.DataFrame(memberData); memberDF

Name  Age      Weight
0   b'Sanjeev'   37  162.399994
1  b'Yingluck'   45  137.800003
2     b'Emeka'   28  153.199997
3       b'Amy'   67  101.300003

In [189]:
pd.DataFrame(memberData, index = ['a', 'b', 'c', 'd'])

Name  Age      Weight
a   b'Sanjeev'   37  162.399994
b  b'Yingluck'   45  137.800003
c     b'Emeka'   28  153.199997
d       b'Amy'   67  101.300003

In [190]:
currSeries.name = 'currency'

In [191]:
pd.DataFrame(currSeries)

currency
China       yuan
Germany     euro
Japan        yen
Mexico      peso
Nigeria    naira
UK         pound
US        dollar

In [192]:
memberDF['Name']

0     b'Sanjeev'
1    b'Yingluck'
2       b'Emeka'
3         b'Amy'
Name: Name, dtype: object

In [193]:
memberDF['Height'] = 60; memberDF

Name  Age      Weight  Height
0   b'Sanjeev'   37  162.399994      60
1  b'Yingluck'   45  137.800003      60
2     b'Emeka'   28  153.199997      60
3       b'Amy'   67  101.300003      60

In [194]:
del memberDF['Height']; memberDF

Name  Age      Weight
0   b'Sanjeev'   37  162.399994
1  b'Yingluck'   45  137.800003
2     b'Emeka'   28  153.199997
3       b'Amy'   67  101.300003

In [195]:
memberDF['BloodType'] = 'O'

In [196]:
bloodType = memberDF.pop('BloodType');

In [197]:
bloodType

0    O
1    O
2    O
3    O
Name: BloodType, dtype: object

In [198]:
memberDF.insert(2, 'isSenior', memberDF['Age']> 60);

In [199]:
memberDF

Name  Age isSenior      Weight
0   b'Sanjeev'   37    False  162.399994
1  b'Yingluck'   45    False  137.800003
2     b'Emeka'   28    False  153.199997
3       b'Amy'   67     True  101.300003

In [200]:
ore1DF=pd.DataFrame(np.array([[20,35,25,20],
                                       [11,28,32,29]]),
                              columns=['iron','magnesium',
                                       'copper','silver'])

In [201]:
ore2DF=pd.DataFrame(np.array([[14,34,26,26],
                                   [33,19,25,23]]),
                             columns=['iron','magnesium',
                                     'gold','silver'])


In [202]:
ore1DF + ore2DF

copper  gold  iron  magnesium  silver
0     NaN   NaN    34         69      46
1     NaN   NaN    44         47      52

In [203]:
ore1DF + pd.Series([25, 25, 25, 25],
                  index = ['iron', 'magnesium', 'copper', 'silver'])

iron  magnesium  copper  silver
0    45         60      50      45
1    36         53      57      54

In [204]:
np.sqrt(ore1DF)

iron  magnesium    copper    silver
0  4.472136   5.916080  5.000000  4.472136
1  3.316625   5.291503  5.656854  5.385165

In [205]:
stockData=np.array([[[63.03,61.48,75],
                           [62.05,62.75,46],
                            [62.74,62.19,53]],
                              [[411.90, 404.38, 2.9],
                               [405.45, 405.91, 2.6],
                               [403.15, 404.42, 2.4]]])

In [206]:
stockData

array([[[  63.03,   61.48,   75.  ],
        [  62.05,   62.75,   46.  ],
        [  62.74,   62.19,   53.  ]],

       [[ 411.9 ,  404.38,    2.9 ],
        [ 405.45,  405.91,    2.6 ],
        [ 403.15,  404.42,    2.4 ]]])

In [209]:
stockHistoricalPrices = pd.Panel(stockData, items = ['FB', 'NFLX'],
                                 major_axis = pd.date_range('2/3/2014', periods = 3),
                                 minor_axis = ['open price', 'closing price', 'volume'])

In [210]:
stockHistoricalPrices

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 3 (minor_axis)
Items axis: FB to NFLX
Major_axis axis: 2014-02-03 00:00:00 to 2014-02-05 00:00:00
Minor_axis axis: open price to volume

In [212]:
USData=pd.DataFrame(np.array([[249.62  , 8900],
                                       [ 282.16,12680],
                                       [309.35,14940]]),
                    columns=['Population(M)','GDP($B)'],
                    index = [1990, 2000, 2010])

In [213]:
USData

Population(M)  GDP($B)
1990         249.62   8900.0
2000         282.16  12680.0
2010         309.35  14940.0

In [214]:
ChinaData=pd.DataFrame(np.array([[1133.68, 390.28],
                                           [ 1266.83,1198.48],
                                           [1339.72, 6988.47]]),
                    columns=['Population(M)','GDP($B)'],
                    index=[1990,2000,2010])

In [215]:
ChinaData

Population(M)  GDP($B)
1990        1133.68   390.28
2000        1266.83  1198.48
2010        1339.72  6988.47

In [216]:
US_ChinaData={'US' : USData,
                       'China': ChinaData}

In [217]:
pd.Panel(US_ChinaData)

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 2 (minor_axis)
Items axis: China to US
Major_axis axis: 1990 to 2010
Minor_axis axis: Population(M) to GDP($B)

In [218]:
mIdx = pd.MultiIndex(levels = [['US', 'China'],
                              [1990, 2000, 2010]],
                    labels = [[1, 1, 1, 0, 0, 0], [0, 1, 2, 0, 1, 2]])

In [219]:
mIdx

MultiIndex(levels=[['US', 'China'], [1990, 2000, 2010]],
           labels=[[1, 1, 1, 0, 0, 0], [0, 1, 2, 0, 1, 2]])

In [220]:
ChinaUSDF = pd.DataFrame({'Population(M)' : [1133.68, 1266.83,
                                             1339.72, 249.62,
                                             282.16,309.35],
                         'GDB($B)': [390.28, 1198.48, 6988.47,
                                     8900,12680, 14940]}, index=mIdx)

In [221]:
ChinaUSDF

GDB($B)  Population(M)
China 1990    390.28        1133.68
      2000   1198.48        1266.83
      2010   6988.47        1339.72
US    1990   8900.00         249.62
      2000  12680.00         282.16
      2010  14940.00         309.35

In [222]:
ChinaUSDF = pd.DataFrame({'Population(M)' : [1133.68,
                             1266.83,
                             1339.72,
                              249.62,
                              282.16,
                              309.35],
           'GDB($B)': [390.28, 1198.48,
                       6988.47, 8900,
                       12680,14940]},
index=mIdx)


In [223]:
ChinaUSDF

GDB($B)  Population(M)
China 1990    390.28        1133.68
      2000   1198.48        1266.83
      2010   6988.47        1339.72
US    1990   8900.00         249.62
      2000  12680.00         282.16
      2010  14940.00         309.35

In [224]:
ChinaUSDF.to_panel()

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 2 (major_axis) x 3 (minor_axis)
Items axis: GDB($B) to Population(M)
Major_axis axis: US to China
Minor_axis axis: 1990 to 2010

In [226]:
SpotCrudePrices_2013_Data={
                'U.K. Brent' : {'2013-Q1':112.9, '2013-Q2':103.0, '2013-Q3':110.1, '2013-Q4':109.4},
                'Dubai':{'2013-Q1':108.1, '2013-Q2':100.8,
'2013-Q3':106.1,'2013-Q4':106.7},
                'West Texas Intermediate':{'2013-Q1':94.4, '2013-Q2':94.2, '2013-Q3':105.8,'2013-Q4':97.4}}

In [227]:
SpotCrudePrices_2013 = pd.DataFrame.from_dict(SpotCrudePrices_2013_Data)

In [228]:
dubaiPrices = SpotCrudePrices_2013['Dubai']; dubaiPrices

2013-Q1    108.1
2013-Q2    100.8
2013-Q3    106.1
2013-Q4    106.7
Name: Dubai, dtype: float64

In [229]:
SpotCrudePrices_2013[['West Texas Intermediate', 'U.K. Brent']]

West Texas Intermediate  U.K. Brent
2013-Q1                     94.4       112.9
2013-Q2                     94.2       103.0
2013-Q3                    105.8       110.1
2013-Q4                     97.4       109.4

In [230]:
SpotCrudePrices_2013['U.K. Brent']

2013-Q1    112.9
2013-Q2    103.0
2013-Q3    110.1
2013-Q4    109.4
Name: U.K. Brent, dtype: float64

In [231]:
SpotCrudePrices_2013.Dubai

2013-Q1    108.1
2013-Q2    100.8
2013-Q3    106.1
2013-Q4    106.7
Name: Dubai, dtype: float64

In [232]:
SpotCrudePrices_2013

Dubai  U.K. Brent  West Texas Intermediate
2013-Q1  108.1       112.9                     94.4
2013-Q2  100.8       103.0                     94.2
2013-Q3  106.1       110.1                    105.8
2013-Q4  106.7       109.4                     97.4

In [233]:
SpotCrudePrices_2013.columns = ['Dubai', 'UK_Brent', 'West_Texas_Intermediate']

In [234]:
SpotCrudePrices_2013

Dubai  UK_Brent  West_Texas_Intermediate
2013-Q1  108.1     112.9                     94.4
2013-Q2  100.8     103.0                     94.2
2013-Q3  106.1     110.1                    105.8
2013-Q4  106.7     109.4                     97.4

In [235]:
SpotCrudePrices_2013.West_Texas_Intermediate

2013-Q1     94.4
2013-Q2     94.2
2013-Q3    105.8
2013-Q4     97.4
Name: West_Texas_Intermediate, dtype: float64

In [237]:
SpotCrudePrices_2013[[0]]

Dubai
2013-Q1  108.1
2013-Q2  100.8
2013-Q3  106.1
2013-Q4  106.7

In [238]:
SpotCrudePrices_2013[:2]

Dubai  UK_Brent  West_Texas_Intermediate
2013-Q1  108.1     112.9                     94.4
2013-Q2  100.8     103.0                     94.2

In [239]:
SpotCrudePrices_2013[2:]

Dubai  UK_Brent  West_Texas_Intermediate
2013-Q3  106.1     110.1                    105.8
2013-Q4  106.7     109.4                     97.4

In [240]:
SpotCrudePrices_2013[::-1]

Dubai  UK_Brent  West_Texas_Intermediate
2013-Q4  106.7     109.4                     97.4
2013-Q3  106.1     110.1                    105.8
2013-Q2  100.8     103.0                     94.2
2013-Q1  108.1     112.9                     94.4

In [241]:
SpotCrudePrices_2013[::2]

Dubai  UK_Brent  West_Texas_Intermediate
2013-Q1  108.1     112.9                     94.4
2013-Q3  106.1     110.1                    105.8

In [242]:
dubaiPrices = SpotCrudePrices_2013['Dubai']

In [243]:
dubaiPrices[1:]

2013-Q2    100.8
2013-Q3    106.1
2013-Q4    106.7
Name: Dubai, dtype: float64

In [245]:
dubaiPrices[:-1]

2013-Q1    108.1
2013-Q2    100.8
2013-Q3    106.1
Name: Dubai, dtype: float64

In [246]:
dubaiPrices[::-1]

2013-Q4    106.7
2013-Q3    106.1
2013-Q2    100.8
2013-Q1    108.1
Name: Dubai, dtype: float64

In [247]:
NYC_SnowAvgsData={'Months' :
['January','February','March',
'April', 'November', 'December'],
'Avg SnowDays' : [4.0,2.7,1.7,0.2,0.2,2.3],
'Avg Precip. (cm)' : [17.8,22.4,9.1,1.5,0.8,12.2],
'Avg Low Temp. (F)' : [27,29,35,45,42,32] }


In [248]:
NYC_SnowAvgsData

{'Avg Low Temp. (F)': [27, 29, 35, 45, 42, 32],
 'Avg Precip. (cm)': [17.8, 22.4, 9.1, 1.5, 0.8, 12.2],
 'Avg SnowDays': [4.0, 2.7, 1.7, 0.2, 0.2, 2.3],
 'Months': ['January', 'February', 'March', 'April', 'November', 'December']}

In [250]:
NYC_SnowAvgs = pd.DataFrame(NYC_SnowAvgsData,
                           index = NYC_SnowAvgsData['Months'],
                           columns = ['Avg SnowDays', 'Avg Precip. (cm)', 
                                     'Avg Low Temp. (F)'])

In [251]:
NYC_SnowAvgs

Avg SnowDays  Avg Precip. (cm)  Avg Low Temp. (F)
January            4.0              17.8                 27
February           2.7              22.4                 29
March              1.7               9.1                 35
April              0.2               1.5                 45
November           0.2               0.8                 42
December           2.3              12.2                 32

In [252]:
NYC_SnowAvgs.loc['January']

Avg SnowDays          4.0
Avg Precip. (cm)     17.8
Avg Low Temp. (F)    27.0
Name: January, dtype: float64

In [253]:
NYC_SnowAvgs.loc[['January', 'April']]

Avg SnowDays  Avg Precip. (cm)  Avg Low Temp. (F)
January           4.0              17.8                 27
April             0.2               1.5                 45

In [254]:
NYC_SnowAvgs.loc['January': 'March']

Avg SnowDays  Avg Precip. (cm)  Avg Low Temp. (F)
January            4.0              17.8                 27
February           2.7              22.4                 29
March              1.7               9.1                 35

In [256]:
NYC_SnowAvgs.loc[:, 'Avg SnowDays']

January     4.0
February    2.7
March       1.7
April       0.2
November    0.2
December    2.3
Name: Avg SnowDays, dtype: float64

In [257]:
NYC_SnowAvgs.loc['March', 'Avg SnowDays']

1.7

In [258]:
NYC_SnowAvgs.loc['March']['Avg SnowDays']

1.7

In [261]:
NYC_SnowAvgs.loc['March']

Avg SnowDays          1.7
Avg Precip. (cm)      9.1
Avg Low Temp. (F)    35.0
Name: March, dtype: float64

In [262]:
NYC_SnowAvgs.loc[NYC_SnowAvgs['Avg SnowDays']<1,:]

Avg SnowDays  Avg Precip. (cm)  Avg Low Temp. (F)
April              0.2               1.5                 45
November           0.2               0.8                 42

In [263]:
SpotCrudePrices_2013.loc[:,SpotCrudePrices_2013.loc['2013-Q1']>110]

UK_Brent
2013-Q1     112.9
2013-Q2     103.0
2013-Q3     110.1
2013-Q4     109.4

In [264]:
SpotCrudePrices_2013.loc['2013-Q1']>110

Dubai                      False
UK_Brent                    True
West_Texas_Intermediate    False
Name: 2013-Q1, dtype: bool

In [265]:
import scipy.constants as phys

In [266]:
import math

In [267]:
sci_values=pd.DataFrame([[math.pi, math.sin(math.pi),
                                    math.cos(math.pi)], [math.e,math.log(math.e),
 phys.golden],
[phys.c,phys.g,phys.e],
[phys.m_e,phys.m_p,phys.m_n]],
index=list(range(0,20,5)))


## Mastering Pandas (page 102 of 364)

In [268]:
sci_values.iloc[:2]

0             1         2
0  3.141593  1.224647e-16 -1.000000
5  2.718282  1.000000e+00  1.618034

In [269]:
sci_values.iloc[2, 0:2]

0    2.997925e+08
1    9.806650e+00
Name: 10, dtype: float64

In [270]:
sci_values.loc[10]

0    2.997925e+08
1    9.806650e+00
2    1.602177e-19
Name: 10, dtype: float64

In [271]:
sci_values.iloc[2:3, :]

0        1             2
10  299792458.0  9.80665  1.602177e-19

In [272]:
sci_values.iloc[3]

0    9.109384e-31
1    1.672622e-27
2    1.674927e-27
Name: 15, dtype: float64

In [273]:
sci_values.iloc[3, 0]

9.1093835599999998e-31

In [275]:
sci_values.iat[3, 0]

9.1093835599999998e-31

In [276]:
%timeit sci_values.iloc[3, 0]

10000 loops, best of 3: 135 µs per loop


In [277]:
%timeit sci_values.iat[3, 0]

The slowest run took 4.52 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 12.2 µs per loop


In [278]:
%%writefile stock_index_data.csv
TradingDate,Nasdaq,S&P 500,Russell 2000
2014/01/30,4123.13,1794.19,1139.36
2014/01/31,4103.88,1782.59,1130.88
2014/02/03,3996.96,1741.89,1094.58
2014/02/04,4031.52,1755.2,1102.84
2014/02/05,4011.55,1751.64,1093.59
2014/02/06,4057.12,1773.43,1103.93

Writing stock_index_data.csv


In [279]:
stockIndexDataDF = pd.read_csv('stock_index_data.csv')

In [280]:
stockIndexDataDF

TradingDate   Nasdaq  S&P 500  Russell 2000
0  2014/01/30  4123.13  1794.19       1139.36
1  2014/01/31  4103.88  1782.59       1130.88
2  2014/02/03  3996.96  1741.89       1094.58
3  2014/02/04  4031.52  1755.20       1102.84
4  2014/02/05  4011.55  1751.64       1093.59
5  2014/02/06  4057.12  1773.43       1103.93

In [281]:
stockIndexDF = stockIndexDataDF.set_index('TradingDate')

In [282]:
stockIndexDF

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36
2014/01/31   4103.88  1782.59       1130.88
2014/02/03   3996.96  1741.89       1094.58
2014/02/04   4031.52  1755.20       1102.84
2014/02/05   4011.55  1751.64       1093.59
2014/02/06   4057.12  1773.43       1103.93

In [283]:
stockIndexDF.ix['2014/01/30']

Nasdaq          4123.13
S&P 500         1794.19
Russell 2000    1139.36
Name: 2014/01/30, dtype: float64

In [284]:
stockIndexDF.ix[['2014/01/30']]

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36

In [285]:
stockIndexDF.ix[['2014/01/30', '2014/01/31']]

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36
2014/01/31   4103.88  1782.59       1130.88

In [286]:
type(stockIndexDF.ix['2014/01/30'])

pandas.core.series.Series

In [287]:
type(stockIndexDF.ix[['2014/01/30']])

pandas.core.frame.DataFrame

In [288]:
tradingDates = stockIndexDataDF.TradingDate

In [289]:
stockIndexDF.ix[tradingDates[:3]]

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36
2014/01/31   4103.88  1782.59       1130.88
2014/02/03   3996.96  1741.89       1094.58

In [290]:
stockIndexDF.ix[0]

Nasdaq          4123.13
S&P 500         1794.19
Russell 2000    1139.36
Name: 2014/01/30, dtype: float64

In [291]:
stockIndexDF.ix[[0, 2]]

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36
2014/02/03   3996.96  1741.89       1094.58

In [292]:
stockIndexDF.ix[1:3]

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/31   4103.88  1782.59       1130.88
2014/02/03   3996.96  1741.89       1094.58

In [293]:
stockIndexDF.ix[stockIndexDF['Russell 2000']>1100]

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36
2014/01/31   4103.88  1782.59       1130.88
2014/02/04   4031.52  1755.20       1102.84
2014/02/06   4057.12  1773.43       1103.93

In [294]:
%%writefile stock_index_prices.csv
TradingDate,PriceType,Nasdaq,S&P 500,Russell 2000
2014/02/21,open,4282.17,1841.07,1166.25
2014/02/21,close,4263.41,1836.25,1164.63
2014/02/21,high,4284.85,1846.13,1168.43
2014/02/24,open,4273.32,1836.78,1166.74
2014/02/24,close,4292.97,1847.61,1174.55
2014/02/24,high,4311.13,1858.71,1180.29
2014/02/25,open,4298.48,1847.66,1176
2014/02/25,close,4287.59,1845.12,1173.95
2014/02/25,high,4307.51,1852.91,1179.43
2014/02/26,open,4300.45,1845.79,1176.11
2014/02/26,close,4292.06,1845.16,1181.72
2014/02/26,high,4316.82,1852.65,1188.06
2014/02/27,open,4291.47,1844.9,1179.28
2014/02/27,close,4318.93,1854.29,1187.94
2014/02/27,high,4322.46,1854.53,1187.94
2014/02/28,open,4323.52,1855.12,1189.19
2014/02/28,close,4308.12,1859.45,1183.03
2014/02/28,high,4342.59,1867.92,1193.5


Writing stock_index_prices.csv


In [295]:
sharesIndexDataDF = pd.read_csv('stock_index_prices.csv')

In [296]:
sharesIndexDataDF

TradingDate PriceType   Nasdaq  S&P 500  Russell 2000
0   2014/02/21      open  4282.17  1841.07       1166.25
1   2014/02/21     close  4263.41  1836.25       1164.63
2   2014/02/21      high  4284.85  1846.13       1168.43
3   2014/02/24      open  4273.32  1836.78       1166.74
4   2014/02/24     close  4292.97  1847.61       1174.55
5   2014/02/24      high  4311.13  1858.71       1180.29
6   2014/02/25      open  4298.48  1847.66       1176.00
7   2014/02/25     close  4287.59  1845.12       1173.95
8   2014/02/25      high  4307.51  1852.91       1179.43
9   2014/02/26      open  4300.45  1845.79       1176.11
10  2014/02/26     close  4292.06  1845.16       1181.72
11  2014/02/26      high  4316.82  1852.65       1188.06
12  2014/02/27      open  4291.47  1844.90       1179.28
13  2014/02/27     close  4318.93  1854.29       1187.94
14  2014/02/27      high  4322.46  1854.53       1187.94
15  2014/02/28      open  4323.52  1855.12       1189.19
16  2014/02/28     close  4308.12  1859.45       1183.03
17  2014/02/28      high  4342.59  1867.92       1193.50

In [298]:
sharesIndexDF=sharesIndexDataDF.set_index(['TradingDate','PriceType'])

In [300]:
mIndex = sharesIndexDataDF.set_index(['TradingDate', 'PriceType'])

In [301]:
mIndex = sharesIndexDF.index; mIndex

MultiIndex(levels=[['2014/02/21', '2014/02/24', '2014/02/25', '2014/02/26', '2014/02/27', '2014/02/28'], ['close', 'high', 'open']],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5], [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1]],
           names=['TradingDate', 'PriceType'])

In [302]:
sharesIndexDF

Nasdaq  S&P 500  Russell 2000
TradingDate PriceType                                
2014/02/21  open       4282.17  1841.07       1166.25
            close      4263.41  1836.25       1164.63
            high       4284.85  1846.13       1168.43
2014/02/24  open       4273.32  1836.78       1166.74
            close      4292.97  1847.61       1174.55
            high       4311.13  1858.71       1180.29
2014/02/25  open       4298.48  1847.66       1176.00
            close      4287.59  1845.12       1173.95
            high       4307.51  1852.91       1179.43
2014/02/26  open       4300.45  1845.79       1176.11
            close      4292.06  1845.16       1181.72
            high       4316.82  1852.65       1188.06
2014/02/27  open       4291.47  1844.90       1179.28
            close      4318.93  1854.29       1187.94
            high       4322.46  1854.53       1187.94
2014/02/28  open       4323.52  1855.12       1189.19
            close      4308.12  1859.45       1183.03
            high       4342.59  1867.92       1193.50

In [303]:
mIndex.get_level_values(0)

Index(['2014/02/21', '2014/02/21', '2014/02/21', '2014/02/24', '2014/02/24',
       '2014/02/24', '2014/02/25', '2014/02/25', '2014/02/25', '2014/02/26',
       '2014/02/26', '2014/02/26', '2014/02/27', '2014/02/27', '2014/02/27',
       '2014/02/28', '2014/02/28', '2014/02/28'],
      dtype='object', name='TradingDate')

In [304]:
mIndex.get_level_values(1)

Index(['open', 'close', 'high', 'open', 'close', 'high', 'open', 'close',
       'high', 'open', 'close', 'high', 'open', 'close', 'high', 'open',
       'close', 'high'],
      dtype='object', name='PriceType')

In [305]:
sharesIndexDF.ix['2014/02/21']

Nasdaq  S&P 500  Russell 2000
PriceType                                
open       4282.17  1841.07       1166.25
close      4263.41  1836.25       1164.63
high       4284.85  1846.13       1168.43

In [306]:
sharesIndexDF.ix['2014/02/21', 'open']

Nasdaq          4282.17
S&P 500         1841.07
Russell 2000    1166.25
Name: (2014/02/21, open), dtype: float64

In [307]:
sharesIndexDF.ix['2014/02/21':'2014/02/24']

Nasdaq  S&P 500  Russell 2000
TradingDate PriceType                                
2014/02/21  open       4282.17  1841.07       1166.25
            close      4263.41  1836.25       1164.63
            high       4284.85  1846.13       1168.43
2014/02/24  open       4273.32  1836.78       1166.74
            close      4292.97  1847.61       1174.55
            high       4311.13  1858.71       1180.29

In [309]:
sharesIndexDF.sortlevel(0).ix[('2014/02/21','open'):('2014/02/24','open')]

Nasdaq  S&P 500  Russell 2000
TradingDate PriceType                                
2014/02/21  open       4282.17  1841.07       1166.25
2014/02/24  close      4292.97  1847.61       1174.55
            high       4311.13  1858.71       1180.29
            open       4273.32  1836.78       1166.74

In [310]:
sharesIndexDF.ix[[('2014/02/21','close'),('2014/02/24','open')]]


Nasdaq  S&P 500  Russell 2000
TradingDate PriceType                                
2014/02/21  close      4263.41  1836.25       1164.63
2014/02/24  open       4273.32  1836.78       1166.74

In [312]:
swappedDF = sharesIndexDF[:7].swaplevel(0, 1, axis = 0)

In [313]:
swappedDF

Nasdaq  S&P 500  Russell 2000
PriceType TradingDate                                
open      2014/02/21   4282.17  1841.07       1166.25
close     2014/02/21   4263.41  1836.25       1164.63
high      2014/02/21   4284.85  1846.13       1168.43
open      2014/02/24   4273.32  1836.78       1166.74
close     2014/02/24   4292.97  1847.61       1174.55
high      2014/02/24   4311.13  1858.71       1180.29
open      2014/02/25   4298.48  1847.66       1176.00

In [314]:
reorderedDF = sharesIndexDF[:7].reorder_levels(['PriceType', 'TradingDate'], axis = 0)

In [315]:
reorderedDF

Nasdaq  S&P 500  Russell 2000
PriceType TradingDate                                
open      2014/02/21   4282.17  1841.07       1166.25
close     2014/02/21   4263.41  1836.25       1164.63
high      2014/02/21   4284.85  1846.13       1168.43
open      2014/02/24   4273.32  1836.78       1166.74
close     2014/02/24   4292.97  1847.61       1174.55
high      2014/02/24   4311.13  1858.71       1180.29
open      2014/02/25   4298.48  1847.66       1176.00

In [316]:
sharesIndexDF.xs('open', level = 'PriceType')

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/02/21   4282.17  1841.07       1166.25
2014/02/24   4273.32  1836.78       1166.74
2014/02/25   4298.48  1847.66       1176.00
2014/02/26   4300.45  1845.79       1176.11
2014/02/27   4291.47  1844.90       1179.28
2014/02/28   4323.52  1855.12       1189.19

In [318]:
sharesIndexDF.swaplevel(0, 1, axis = 0).ix['open']

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/02/21   4282.17  1841.07       1166.25
2014/02/24   4273.32  1836.78       1166.74
2014/02/25   4298.48  1847.66       1176.00
2014/02/26   4300.45  1845.79       1176.11
2014/02/27   4291.47  1844.90       1179.28
2014/02/28   4323.52  1855.12       1189.19

In [320]:
sharesIndexDataDF.ix[(sharesIndexDataDF['PriceType']=='close') & (sharesIndexDataDF['Nasdaq']>4300) ]

TradingDate PriceType   Nasdaq  S&P 500  Russell 2000
13  2014/02/27     close  4318.93  1854.29       1187.94
16  2014/02/28     close  4308.12  1859.45       1183.03

In [321]:
stockSeries=pd.Series(['NFLX','AMZN','GOOG','FB','TWTR'])

In [322]:
stockSeries.isin(['AMZN', 'FB'])

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [323]:
stockSeries[stockSeries.isin(['AMZN', 'FB'])]

1    AMZN
3      FB
dtype: object

In [1]:
australianMammals = {'kangaroo' : {'Subclass':'marsupial', 'Species Origin': 'native'},
'flying fox' : {'Subclass': 'placental', 'Species Origin': 'native'},
'black rat': {'Subclass': 'placental', 'Species Origin': 'invasive'},
'platypus': {'Subclass': 'monotreme', 'Species Origin': 'native'},
'wallaby': {'Subclass': 'marsupial', 'Species Origin': 'native'},
'palm squirrel' : {'Subclass': 'placental', 'Origin': 'invasive'},
'anteater': {'Subclass': 'monotreme', 'Origin': 'native'},
'koala': {'Subclass': 'marsupial', 'Origin': 'native'}}

# Mastering Pandas (page 117 or 364)

In [3]:
import pandas as pd
ozzieMammalsDF=pd.DataFrame(australianMammals)

In [4]:
aussieMammalsDF=ozzieMammalsDF.T; aussieMammalsDF

Origin Species Origin   Subclass
anteater         native            NaN  monotreme
black rat           NaN       invasive  placental
flying fox          NaN         native  placental
kangaroo            NaN         native  marsupial
koala            native            NaN  marsupial
palm squirrel  invasive            NaN  placental
platypus            NaN         native  monotreme
wallaby             NaN         native  marsupial

In [5]:
aussieMammalsDF.isin({'Subclass':['marsupial'],'Origin':['native']})

Origin Species Origin Subclass
anteater        True          False    False
black rat      False          False    False
flying fox     False          False    False
kangaroo       False          False     True
koala           True          False     True
palm squirrel  False          False    False
platypus       False          False    False
wallaby        False          False     True

In [6]:
nativeMarsupials={'Mammal Subclass':['marsupial'],
                            'Species Origin':['native']}

In [9]:
import numpy as np
np.random.seed(100)

In [10]:
normvals = pd.Series([np.random.normal() for i in np.arange(10)])

In [11]:
normvals

0   -1.749765
1    0.342680
2    1.153036
3   -0.252436
4    0.981321
5    0.514219
6    0.221180
7   -1.070043
8   -0.189496
9    0.255001
dtype: float64

In [12]:
normvals[normvals>0]

1    0.342680
2    1.153036
4    0.981321
5    0.514219
6    0.221180
9    0.255001
dtype: float64

In [13]:
normvals.where(normvals>0)

0         NaN
1    0.342680
2    1.153036
3         NaN
4    0.981321
5    0.514219
6    0.221180
7         NaN
8         NaN
9    0.255001
dtype: float64

In [14]:
np.random.seed(100)

In [15]:
normDF = pd.DataFrame([[round(np.random.normal(), 3) for i in np.arange(5)] for j in range(3)],
                     columns = ['0', '30', '60', '90', '120'])

In [16]:
normDF

0     30     60     90    120
0 -1.750  0.343  1.153 -0.252  0.981
1  0.514  0.221 -1.070 -0.189  0.255
2 -0.458  0.435 -0.584  0.817  0.673

In [17]:
normDF[normDF>0]

0     30     60     90    120
0    NaN  0.343  1.153    NaN  0.981
1  0.514  0.221    NaN    NaN  0.255
2    NaN  0.435    NaN  0.817  0.673

In [18]:
normDF.where(normDF>0)

0     30     60     90    120
0    NaN  0.343  1.153    NaN  0.981
1  0.514  0.221    NaN    NaN  0.255
2    NaN  0.435    NaN  0.817  0.673

In [19]:
normDF.mask(normDF>0)

0  30     60     90  120
0 -1.750 NaN    NaN -0.252  NaN
1    NaN NaN -1.070 -0.189  NaN
2 -0.458 NaN -0.584    NaN  NaN

In [20]:
stockIndexDataDF = pd.read_csv('stock_index_data.csv')

In [21]:
stockIndexDataDF

TradingDate   Nasdaq  S&P 500  Russell 2000
0  2014/01/30  4123.13  1794.19       1139.36
1  2014/01/31  4103.88  1782.59       1130.88
2  2014/02/03  3996.96  1741.89       1094.58
3  2014/02/04  4031.52  1755.20       1102.84
4  2014/02/05  4011.55  1751.64       1093.59
5  2014/02/06  4057.12  1773.43       1103.93

In [22]:
stockIndexDF = stockIndexDataDF.set_index('TradingDate')

In [23]:
stockIndexDF

Nasdaq  S&P 500  Russell 2000
TradingDate                                
2014/01/30   4123.13  1794.19       1139.36
2014/01/31   4103.88  1782.59       1130.88
2014/02/03   3996.96  1741.89       1094.58
2014/02/04   4031.52  1755.20       1102.84
2014/02/05   4011.55  1751.64       1093.59
2014/02/06   4057.12  1773.43       1103.93

In [24]:
stockIndexDF.reset_index()

TradingDate   Nasdaq  S&P 500  Russell 2000
0  2014/01/30  4123.13  1794.19       1139.36
1  2014/01/31  4103.88  1782.59       1130.88
2  2014/02/03  3996.96  1741.89       1094.58
3  2014/02/04  4031.52  1755.20       1102.84
4  2014/02/05  4011.55  1751.64       1093.59
5  2014/02/06  4057.12  1773.43       1103.93

In [25]:
algos={'search':['DFS','BFS','Binary Search','Linear'],
        'sorting': ['Quicksort','Mergesort','Heapsort','Bubble Sort'],
       'machine learning':['RandomForest','K Nearest Neighbor','Logistic Regression','K-Means Clustering']}

In [26]:
algoDF = pd.DataFrame(algos); algoDF

machine learning         search      sorting
0         RandomForest            DFS    Quicksort
1   K Nearest Neighbor            BFS    Mergesort
2  Logistic Regression  Binary Search     Heapsort
3   K-Means Clustering         Linear  Bubble Sort

In [27]:
moreAlgos={'search': 'ShortestPath'  , 'sorting': 'Insertion Sort',
            'machine learning': 'Linear Regression'}
    

In [28]:
algoDF.append(moreAlgos, ignore_index = True)

machine learning         search         sorting
0         RandomForest            DFS       Quicksort
1   K Nearest Neighbor            BFS       Mergesort
2  Logistic Regression  Binary Search        Heapsort
3   K-Means Clustering         Linear     Bubble Sort
4    Linear Regression   ShortestPath  Insertion Sort

In [30]:
plantGrowthRawDF = pd.read_csv("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/PlantGrowth.csv")

In [31]:
plantGrowthRawDF

Unnamed: 0  weight group
0            1    4.17  ctrl
1            2    5.58  ctrl
2            3    5.18  ctrl
3            4    6.11  ctrl
4            5    4.50  ctrl
5            6    4.61  ctrl
6            7    5.17  ctrl
7            8    4.53  ctrl
8            9    5.33  ctrl
9           10    5.14  ctrl
10          11    4.81  trt1
11          12    4.17  trt1
12          13    4.41  trt1
13          14    3.59  trt1
14          15    5.87  trt1
15          16    3.83  trt1
16          17    6.03  trt1
17          18    4.89  trt1
18          19    4.32  trt1
19          20    4.69  trt1
20          21    6.31  trt2
21          22    5.12  trt2
22          23    5.54  trt2
23          24    5.50  trt2
24          25    5.37  trt2
25          26    5.29  trt2
26          27    4.92  trt2
27          28    6.15  trt2
28          29    5.80  trt2
29          30    5.26  trt2

In [32]:
plantGrowthRawDF[plantGrowthRawDF['group'] == 'ctrl']

Unnamed: 0  weight group
0           1    4.17  ctrl
1           2    5.58  ctrl
2           3    5.18  ctrl
3           4    6.11  ctrl
4           5    4.50  ctrl
5           6    4.61  ctrl
6           7    5.17  ctrl
7           8    4.53  ctrl
8           9    5.33  ctrl
9          10    5.14  ctrl

In [34]:
plantGrowthRawDF.pivot(index = 'Unnamed: 0', columns = 'group', values = 'weight')

group       ctrl  trt1  trt2
Unnamed: 0                  
1           4.17   NaN   NaN
2           5.58   NaN   NaN
3           5.18   NaN   NaN
4           6.11   NaN   NaN
5           4.50   NaN   NaN
6           4.61   NaN   NaN
7           5.17   NaN   NaN
8           4.53   NaN   NaN
9           5.33   NaN   NaN
10          5.14   NaN   NaN
11           NaN  4.81   NaN
12           NaN  4.17   NaN
13           NaN  4.41   NaN
14           NaN  3.59   NaN
15           NaN  5.87   NaN
16           NaN  3.83   NaN
17           NaN  6.03   NaN
18           NaN  4.89   NaN
19           NaN  4.32   NaN
20           NaN  4.69   NaN
21           NaN   NaN  6.31
22           NaN   NaN  5.12
23           NaN   NaN  5.54
24           NaN   NaN  5.50
25           NaN   NaN  5.37
26           NaN   NaN  5.29
27           NaN   NaN  4.92
28           NaN   NaN  6.15
29           NaN   NaN  5.80
30           NaN   NaN  5.26

In [42]:
pd.pivot_table(plantGrowthRawDF, values = 'weight', 
              index = 'Unnamed: 0', columns = ['group'])

group       ctrl  trt1  trt2
Unnamed: 0                  
1           4.17   NaN   NaN
2           5.58   NaN   NaN
3           5.18   NaN   NaN
4           6.11   NaN   NaN
5           4.50   NaN   NaN
6           4.61   NaN   NaN
7           5.17   NaN   NaN
8           4.53   NaN   NaN
9           5.33   NaN   NaN
10          5.14   NaN   NaN
11           NaN  4.81   NaN
12           NaN  4.17   NaN
13           NaN  4.41   NaN
14           NaN  3.59   NaN
15           NaN  5.87   NaN
16           NaN  3.83   NaN
17           NaN  6.03   NaN
18           NaN  4.89   NaN
19           NaN  4.32   NaN
20           NaN  4.69   NaN
21           NaN   NaN  6.31
22           NaN   NaN  5.12
23           NaN   NaN  5.54
24           NaN   NaN  5.50
25           NaN   NaN  5.37
26           NaN   NaN  5.29
27           NaN   NaN  4.92
28           NaN   NaN  6.15
29           NaN   NaN  5.80
30           NaN   NaN  5.26

In [43]:
pd.pivot_table(plantGrowthRawDF, values = 'weight', columns = ['group'], aggfunc = np.mean)

group
ctrl    5.032
trt1    4.661
trt2    5.526
Name: weight, dtype: float64

In [45]:
plantGrowthRawDF.set_index(['group', 'Unnamed: 0'])

weight
group Unnamed: 0        
ctrl  1             4.17
      2             5.58
      3             5.18
      4             6.11
      5             4.50
      6             4.61
      7             5.17
      8             4.53
      9             5.33
      10            5.14
trt1  11            4.81
      12            4.17
      13            4.41
      14            3.59
      15            5.87
      16            3.83
      17            6.03
      18            4.89
      19            4.32
      20            4.69
trt2  21            6.31
      22            5.12
      23            5.54
      24            5.50
      25            5.37
      26            5.29
      27            4.92
      28            6.15
      29            5.80
      30            5.26

In [46]:
plantGrowthRawDF.index

RangeIndex(start=0, stop=30, step=1)

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [50]:
date_stngs = ['2014-05-01','2014-05-02',
                       '2014-05-05','2014-05-06','2014-05-07']
tradeDates = pd.to_datetime(pd.Series(date_stngs))

In [51]:
closingPrices=[531.35,527.93,527.81,515.14,509.96]

In [52]:
googClosingPrices = pd.DataFrame(data = closingPrices, columns = ['closingPrice'],
                                index = tradeDates)

In [54]:
googClosingPrices

closingPrice
2014-05-01        531.35
2014-05-02        527.93
2014-05-05        527.81
2014-05-06        515.14
2014-05-07        509.96

In [55]:
import pandas.io.data as web

//anaconda/lib/python3.5/site-packages/pandas/io/data.py:35: FutureWarning: 
The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)


In [57]:
import datetime

In [60]:
xmasDay = pd.datetime(2014, 12, 25)

In [61]:
xmasDay

datetime.datetime(2014, 12, 25, 0, 0)

In [62]:
boxingDay = xmasDay+pd.DateOffset(days = 1)

In [63]:
boxingDay

Timestamp('2014-12-26 00:00:00')

In [65]:
today = pd.datetime.now()

In [66]:
today

datetime.datetime(2016, 6, 26, 17, 12, 3, 603870)

In [67]:
today + pd.DateOffset(weeks = 1)

Timestamp('2016-07-03 17:12:03.603870')

In [68]:
today + 2*pd.DateOffset(years = 2, months = 6)

Timestamp('2021-06-26 17:12:03.603870')

In [69]:
lastDay = pd.datetime(2013, 12, 31)

In [70]:
from pandas.tseries.offsets import QuarterBegin

In [71]:
dfoffset = QuarterBegin()

In [72]:
lastDay+dfoffset

Timestamp('2014-03-01 00:00:00')

In [74]:
dfoffset.rollforward(lastDay)

Timestamp('2014-03-01 00:00:00')