In [1]:
import numpy as np

In [2]:
ar1 = np.array([0, 1, 2, 3])

In [3]:
ar2 = np.array([[0,3, 5], [2, 8, 7]])

In [4]:
ar1

array([0, 1, 2, 3])

In [5]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [6]:
ar2.shape

(2, 3)

In [7]:
ar2.ndim

2

In [8]:
ar3 = np.arange(12); 

In [9]:
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
ar4 = np.arange(3, 10, 3); ar4

array([3, 6, 9])

In [11]:
# args - start element, end element, number of elements
ar5 = np.linspace(0, 2.0/3.4); ar5

array([ 0.        ,  0.0120048 ,  0.0240096 ,  0.03601441,  0.04801921,
        0.06002401,  0.07202881,  0.08403361,  0.09603842,  0.10804322,
        0.12004802,  0.13205282,  0.14405762,  0.15606242,  0.16806723,
        0.18007203,  0.19207683,  0.20408163,  0.21608643,  0.22809124,
        0.24009604,  0.25210084,  0.26410564,  0.27611044,  0.28811525,
        0.30012005,  0.31212485,  0.32412965,  0.33613445,  0.34813926,
        0.36014406,  0.37214886,  0.38415366,  0.39615846,  0.40816327,
        0.42016807,  0.43217287,  0.44417767,  0.45618247,  0.46818727,
        0.48019208,  0.49219688,  0.50420168,  0.51620648,  0.52821128,
        0.54021609,  0.55222089,  0.56422569,  0.57623049,  0.58823529])

In [12]:
# Produces 2x3x2 array of 1's
ar7 = np.ones((2, 3, 2)); ar7

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [13]:
ar8 = np.zeros((4, 2));ar8

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
ar10 = np.diag((2, 1, 4, 6));ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [16]:
# Using the rand, radn functions
np.random.seed(100)
ar11 = np.random.rand(3); ar11

array([ 0.54340494,  0.27836939,  0.42451759])

In [17]:
ar12 = np.random.rand(5); ar12

array([ 0.84477613,  0.00471886,  0.12156912,  0.67074908,  0.82585276])

In [18]:
ar13 = np.empty((3, 2)); ar13

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [19]:
np.array([[1, 2], [6, 7]])

array([[1, 2],
       [6, 7]])

In [20]:
np.tile(np.array([[1, 2], [6, 7]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [21]:
np.tile(np.array([[1, 2], [6, 7]]), (2, 2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])